# Generated by Django 4.0.1 on 2022-01-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_home_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
